# Generated by Django 3.1.5 on 2021-02-08 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210130_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='uploadpdf',
        ),
    ]
