# Generated by Django 3.1.5 on 2021-02-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_uploadpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='arrang_post',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
