# Generated by Django 3.1.5 on 2021-03-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210308_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='arrang_post',
            field=models.IntegerField(),
        ),
    ]
